/**
 * Gallery Demo — /gallery/demo
 *
 * Static demo route that renders GalleryViewer with hardcoded mock data.
 * Skips Supabase entirely — used by QA to visually verify Gallery Viewer,
 * Gallery Lightbox, and related flows without a live database record.
 *
 * QA tasks unblocked:
 *   - [QA] Gallery Viewer — GID: 1213962091596794
 *   - [QA] Gallery Lightbox & Navigation — GID: 1213959136922876
 */

import type { Metadata } from 'next'
import { GalleryViewer } from '@/components/features/client-portal/GalleryViewer'
import type { Gallery, Media } from '@/types/supabase'

export const metadata: Metadata = {
  title: 'Johnson Wedding — June 2026 | Sarah Chen Photography',
  description: 'View your gallery from Sarah Chen Photography',
  robots: { index: false, follow: false },
}

// ---------------------------------------------------------------------------
// Mock gallery record
// ---------------------------------------------------------------------------

const DEMO_GALLERY: Gallery = {
  id: 'demo',
  project_id: 'demo-project',
  workspace_id: 'demo-workspace',
  title: 'Johnson Wedding — June 2026',
  cover_photo_url: 'https://picsum.photos/seed/ceremony1/1200/800',
  password_protected: false,
  password_hash: null,
  allow_downloads: true,
  show_powered_by: false,
  photographer_name: 'Sarah Chen Photography',
  photographer_logo_url: null,
  theme: 'dark',
  status: 'published',
  expires_at: null,
  created_at: '2026-06-15T10:00:00Z',
  updated_at: '2026-06-15T10:00:00Z',
}

// ---------------------------------------------------------------------------
// Mock media — 16 photos across 4 categories
// ---------------------------------------------------------------------------

const DEMO_MEDIA: Media[] = [
  // ── Ceremony ──────────────────────────────────────────────────────────────
  {
    id: 'demo-c1',
    project_id: 'demo-project',
    storage_path: 'demo/ceremony-1.jpg',
    filename: 'ceremony-1.jpg',
    display_name: 'First Kiss',
    mime_type: 'image/jpeg',
    size_bytes: 4200000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/ceremony1/800/533',
    watermarked_url: null,
    ai_category: 'Ceremony',
    ai_confidence: 0.97,
    ai_labels: null,
    sort_order: 1,
    created_at: '2026-06-15T14:00:00Z',
  },
  {
    id: 'demo-c2',
    project_id: 'demo-project',
    storage_path: 'demo/ceremony-2.jpg',
    filename: 'ceremony-2.jpg',
    display_name: 'Ring Exchange',
    mime_type: 'image/jpeg',
    size_bytes: 3800000,
    width: 3840,
    height: 5760,
    orientation: 'portrait',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/ceremony2/533/800',
    watermarked_url: null,
    ai_category: 'Ceremony',
    ai_confidence: 0.94,
    ai_labels: null,
    sort_order: 2,
    created_at: '2026-06-15T14:05:00Z',
  },
  {
    id: 'demo-c3',
    project_id: 'demo-project',
    storage_path: 'demo/ceremony-3.jpg',
    filename: 'ceremony-3.jpg',
    display_name: 'Aisle Walk',
    mime_type: 'image/jpeg',
    size_bytes: 4500000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/ceremony3/800/533',
    watermarked_url: null,
    ai_category: 'Ceremony',
    ai_confidence: 0.92,
    ai_labels: null,
    sort_order: 3,
    created_at: '2026-06-15T14:10:00Z',
  },
  {
    id: 'demo-c4',
    project_id: 'demo-project',
    storage_path: 'demo/ceremony-4.jpg',
    filename: 'ceremony-4.jpg',
    display_name: 'Ceremony Venue',
    mime_type: 'image/jpeg',
    size_bytes: 3200000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/ceremony4/800/533',
    watermarked_url: null,
    ai_category: 'Ceremony',
    ai_confidence: 0.89,
    ai_labels: null,
    sort_order: 4,
    created_at: '2026-06-15T14:15:00Z',
  },

  // ── Reception ─────────────────────────────────────────────────────────────
  {
    id: 'demo-r1',
    project_id: 'demo-project',
    storage_path: 'demo/reception-1.jpg',
    filename: 'reception-1.jpg',
    display_name: 'First Dance',
    mime_type: 'image/jpeg',
    size_bytes: 5100000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/reception1/800/533',
    watermarked_url: null,
    ai_category: 'Reception',
    ai_confidence: 0.96,
    ai_labels: null,
    sort_order: 5,
    created_at: '2026-06-15T18:00:00Z',
  },
  {
    id: 'demo-r2',
    project_id: 'demo-project',
    storage_path: 'demo/reception-2.jpg',
    filename: 'reception-2.jpg',
    display_name: 'Cake Cutting',
    mime_type: 'image/jpeg',
    size_bytes: 3600000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/reception2/800/533',
    watermarked_url: null,
    ai_category: 'Reception',
    ai_confidence: 0.93,
    ai_labels: null,
    sort_order: 6,
    created_at: '2026-06-15T18:30:00Z',
  },
  {
    id: 'demo-r3',
    project_id: 'demo-project',
    storage_path: 'demo/reception-3.jpg',
    filename: 'reception-3.jpg',
    display_name: 'Toasts',
    mime_type: 'image/jpeg',
    size_bytes: 4100000,
    width: 3840,
    height: 5760,
    orientation: 'portrait',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/reception3/533/800',
    watermarked_url: null,
    ai_category: 'Reception',
    ai_confidence: 0.88,
    ai_labels: null,
    sort_order: 7,
    created_at: '2026-06-15T19:00:00Z',
  },
  {
    id: 'demo-r4',
    project_id: 'demo-project',
    storage_path: 'demo/reception-4.jpg',
    filename: 'reception-4.jpg',
    display_name: 'Dance Floor',
    mime_type: 'image/jpeg',
    size_bytes: 4800000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/reception4/800/533',
    watermarked_url: null,
    ai_category: 'Reception',
    ai_confidence: 0.91,
    ai_labels: null,
    sort_order: 8,
    created_at: '2026-06-15T19:30:00Z',
  },

  // ── Portraits ─────────────────────────────────────────────────────────────
  {
    id: 'demo-p1',
    project_id: 'demo-project',
    storage_path: 'demo/portrait-1.jpg',
    filename: 'portrait-1.jpg',
    display_name: 'Couple Portrait',
    mime_type: 'image/jpeg',
    size_bytes: 4400000,
    width: 3840,
    height: 5760,
    orientation: 'portrait',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/portrait1/533/800',
    watermarked_url: null,
    ai_category: 'Portraits',
    ai_confidence: 0.98,
    ai_labels: null,
    sort_order: 9,
    created_at: '2026-06-15T16:00:00Z',
  },
  {
    id: 'demo-p2',
    project_id: 'demo-project',
    storage_path: 'demo/portrait-2.jpg',
    filename: 'portrait-2.jpg',
    display_name: 'Golden Hour',
    mime_type: 'image/jpeg',
    size_bytes: 5200000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/portrait2/800/533',
    watermarked_url: null,
    ai_category: 'Portraits',
    ai_confidence: 0.96,
    ai_labels: null,
    sort_order: 10,
    created_at: '2026-06-15T16:15:00Z',
  },
  {
    id: 'demo-p3',
    project_id: 'demo-project',
    storage_path: 'demo/portrait-3.jpg',
    filename: 'portrait-3.jpg',
    display_name: 'Bridal Party',
    mime_type: 'image/jpeg',
    size_bytes: 6100000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/portrait3/800/533',
    watermarked_url: null,
    ai_category: 'Portraits',
    ai_confidence: 0.94,
    ai_labels: null,
    sort_order: 11,
    created_at: '2026-06-15T16:30:00Z',
  },
  {
    id: 'demo-p4',
    project_id: 'demo-project',
    storage_path: 'demo/portrait-4.jpg',
    filename: 'portrait-4.jpg',
    display_name: 'Family Formals',
    mime_type: 'image/jpeg',
    size_bytes: 5800000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/portrait4/800/533',
    watermarked_url: null,
    ai_category: 'Portraits',
    ai_confidence: 0.90,
    ai_labels: null,
    sort_order: 12,
    created_at: '2026-06-15T16:45:00Z',
  },

  // ── Details ───────────────────────────────────────────────────────────────
  {
    id: 'demo-d1',
    project_id: 'demo-project',
    storage_path: 'demo/details-1.jpg',
    filename: 'details-1.jpg',
    display_name: 'Wedding Rings',
    mime_type: 'image/jpeg',
    size_bytes: 2800000,
    width: 4000,
    height: 4000,
    orientation: 'square',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/details1/600/600',
    watermarked_url: null,
    ai_category: 'Details',
    ai_confidence: 0.99,
    ai_labels: null,
    sort_order: 13,
    created_at: '2026-06-15T12:00:00Z',
  },
  {
    id: 'demo-d2',
    project_id: 'demo-project',
    storage_path: 'demo/details-2.jpg',
    filename: 'details-2.jpg',
    display_name: 'Bouquet',
    mime_type: 'image/jpeg',
    size_bytes: 3100000,
    width: 3840,
    height: 5760,
    orientation: 'portrait',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/details2/533/800',
    watermarked_url: null,
    ai_category: 'Details',
    ai_confidence: 0.97,
    ai_labels: null,
    sort_order: 14,
    created_at: '2026-06-15T12:15:00Z',
  },
  {
    id: 'demo-d3',
    project_id: 'demo-project',
    storage_path: 'demo/details-3.jpg',
    filename: 'details-3.jpg',
    display_name: 'Table Setting',
    mime_type: 'image/jpeg',
    size_bytes: 3500000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/details3/800/533',
    watermarked_url: null,
    ai_category: 'Details',
    ai_confidence: 0.93,
    ai_labels: null,
    sort_order: 15,
    created_at: '2026-06-15T12:30:00Z',
  },
  {
    id: 'demo-d4',
    project_id: 'demo-project',
    storage_path: 'demo/details-4.jpg',
    filename: 'details-4.jpg',
    display_name: 'Invitations',
    mime_type: 'image/jpeg',
    size_bytes: 2600000,
    width: 5760,
    height: 3840,
    orientation: 'landscape',
    cloudflare_image_id: null,
    thumbnail_url: 'https://picsum.photos/seed/details4/800/533',
    watermarked_url: null,
    ai_category: 'Details',
    ai_confidence: 0.91,
    ai_labels: null,
    sort_order: 16,
    created_at: '2026-06-15T12:45:00Z',
  },
]

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function GalleryDemoPage() {
  return (
    <GalleryViewer
      gallery={DEMO_GALLERY}
      media={DEMO_MEDIA}
      photographerName="Sarah Chen Photography"
      photographerLogoUrl={null}
      isPaidPlan={true}
      accessLevel="delivered"
    />
  )
}
